### ISSUE TITLE
Run multiple commands

### ISSUE THREAD

**Issue by anvodev** [coolcorexix/ding#1]
My use case is I need to run multiple commands. For example:
1. docker build
2. docker tag
3. docker push
Can you support this case? That I can run multiple commands and then watch youtube until it alert me after done? :)

**Comment by coolcorexix** [comment]
Thank you for your feedback, in case you want to run multiple command then ring a sound, you can use ding's second syntax 

```
docker build && docker tag && docker push && ding
```
Let me add this info to the README
